/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Home { 
    body?: string;
}

